spring.application.name=appspringsecurity
spring.datasource.url=jdbc:mysql://localhost:3306/GourmetDB?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql